---
## Get code
# git clone https://github.com/tootsuite/mastodon.git live && cd live
# git checkout $(git tag -l | grep -v 'rc[0-9]*$' | sort -V | tail -n 1)

## Install deps
# bundle config deployment 'true'
# bundle config without 'development test'
# bundle install -j$(getconf _NPROCESSORS_ONLN)
# yarn install --pure-lockfile

## MANUALLY??? Run setup wizard
# RAILS_ENV=production bundle exec rake mastodon:setup

# Set up systemd services
# cp /home/mastodon/live/dist/mastodon-*.service /etc/systemd/system/
# systemctl daemon-reload
# systemctl enable --now mastodon-web mastodon-sidekiq mastodon-streaming
