---
- name: Create admin user account.
  user:
    name: "{{ admin_user }}"
    createhome: yes
    home: "/home/{{ admin_user }}"
    generate_ssh_key: yes
    ssh_key_comment: "ansible-{{ inventory_hostname }}"
    password: "{{ admin_password }}"
    groups: "{{ admin_group }}"
    shell: /bin/bash

- name: Add Mastodon user.
  ansible.builtin.user:
    name: "{{ mastodon_user }}"
    shell: /sbin/nologin
    create_home: no
    state: present
